app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class ModelExample(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    col_example = db.Column(db.String(10))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired

class ExampleForm(FlaskForm):
    example_input = StringField("Example input", [InputRequired("Input required")])
    example_submit = SubmitField()


def get_error_str(form):
    '''Returns string in format: [Field label]: [error 1, error 2...]; [other errors...]'''
    errs = [f"{getattr(form, f).label.text}: {', '.join(m)}" for f, m in form.errors.items()]
    return "; ".join(errs)

app/__init__.py
import os
from dotenv import load_dotenv
from flask import Flask
import config, config_debug
from .models import db
from flask_migrate import Migrate

def create_app():
    app = Flask(__name__)

    conf_obj = config
    load_dotenv()
    if os.getenv('FLASK_DEBUG'):
        print('\033[91mDEVELOPMENT MODE SET\033[0m')
        conf_obj = config_debug
    else:
        print('\033[91mPRODUCTION MODE SET\033[0m')
    
    app.config.from_object(conf_obj)

    from .routes import main
    app.register_blueprint(main)


    db.init_app(app)
    migrate = Migrate(app, db)

    return app

#TEST MODIFICATION

app/routes.py
from flask import (
    Blueprint,
    render_template,
    send_from_directory,
    flash,
    redirect,
    url_for,
    current_app,
    request
)
from .forms import *

main = Blueprint('main', __name__)

@main.route("/test/static/<path:filename>", methods=["GET"])
def static_dir(filename):
    return send_from_directory(current_app.static_folder, filename)

@main.route("/test")
def index():
    return render_template("index.html")

@main.route("/test/formexample", methods=["GET", "POST"])
def formexample():
    form = ExampleForm()

    try:
        if request.method == "POST":
            if not form.validate_on_submit():
                raise Exception(get_error_str(form))
            flash('Success', 'info')
            redirect(url_for('main.index'))
    except Exception as e:
        flash(str(e), 'danger')
        print(e)

    return render_template("form.html", form=form)

app/templates/form.html
{% extends "index.html" %}
{% block form %}
<form method="POST">
    <ul class="error">
      {% for e in get_flashed_messages() %}
        <li>{{e}}</li>
      {% endfor %}
      </ul>
    {{form.csrf_token}}
    {{form.example_input}}
    {{form.example_submit}}
</form>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" http-equiv="content-type" content="width=device-width; text/html; charset=UTF-8">
    <title>Test</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('main.static_dir', filename='css/main.css')}}"/>
  </head>
  <body>
    TEST SUCCESS
    <img style="width:100px" src="/test/static/img/test.png">
    {% block form %}
    {% endblock %}
  </body>
</html>